### ISSUE TITLE
Bug - undefined is not object (evaluating 'result.selectitem.value')

### ISSUE THREAD

**Issue by Angelk90** [hectahertz/react-native-material-dialog#33] opened 2018-02-26 17:30 UTC
@hectahertz : 
Hi, I'm using "SinglePickerMaterialDialog",
I realized, if by mistake the user does not press any of the proposed options and then presses on "OK".
The following error is given:
Bug - undefined is not object (evaluating 'result.selectitem.value')

It would be possible to consider the case in which the user does not press anything and press ok.
So not from this mistake.

**Comment by hectahertz** [comment] 2018-03-04 20:16
Hi @Angelk90, thanks for the issue!

From what I can see I'd say the problem is happening on the callback and not inside the component, could you provide some sample code so I can help you?

In any case, I think a better fix for this would be to avoid that state by [preselecting the first option](https://www.nngroup.com/articles/radio-buttons-default-selection/).

What do you think?

**Comment by Angelk90** [comment] 2018-03-05 14:15
@hectahertz : 
just use: https://github.com/hectahertz/react-native-material-dialog#singlepickermaterialdialog
Do not select any items, press ok, it gives you a very simple error.

In my opinion the possible solutions would be two:
1) preselecting the first option.
2) give the user the ability to set a default items.

My personal opinion would be to do so:
Give the user the ability to set a default items, if the user does not set any default items, only then preselecting the first option.

**Comment by hectahertz** [comment] 2018-03-19 17:24
Hi @Angelk90,

As `selectedItem` is something required for the logic of a radio button, I'll update the propTypes so that it doesn't get into this case.

I'd rather keep the default setting logic out of the library as I think it depends on the use case. The consumer of the component should then code the desired behaviour when instantiating the component.

Thanks for reporting this.

**Comment by Angelk90** [comment] 2018-03-26 13:04
@hectahertz : It is not very clear to me.
So what would you do?

**Comment by hectahertz** [comment] 2018-04-04 12:04
@Angelk90 You can check the example app, there's an example [here](https://github.com/hectahertz/react-native-material-dialog/blob/master/example/App.js#L333) that [has the `selectedItem` set to undefined](https://github.com/hectahertz/react-native-material-dialog/blob/master/example/App.js#L37) and it doesn't throw any errors when closing it without selecting an item.

I'd say the problem is in your `onOk` callback code (I can't confirm without you providing some code), as when there's nothing selected, that callback will receive an `undefined` `result`.

If you want to preselect the first option, you can set `selectedItem` to an initial value that corresponds to the first option.

I'll close the issue as the example is working as expected.

**Closed by hectahertz** 2018-04-04 12:04 UTC
Labels: bug
